-- ============================================================
-- Migration: create profiles and lesson_history tables
-- ============================================================

-- ── 1. profiles ─────────────────────────────────────────────
-- One row per authenticated user.
-- Created automatically via trigger when a user signs up.

CREATE TABLE IF NOT EXISTS public.profiles (
  id               UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email            TEXT,
  plan             TEXT        NOT NULL DEFAULT 'gratis'
                               CHECK (plan IN ('gratis', 'pro', 'max')),
  lessons_today    INTEGER     NOT NULL DEFAULT 0,
  last_lesson_date DATE        NOT NULL DEFAULT CURRENT_DATE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every change
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── 2. lesson_history ───────────────────────────────────────
-- Stores every lesson generated by an authenticated user.

CREATE TABLE IF NOT EXISTS public.lesson_history (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  subject     TEXT        NOT NULL,
  lesson_data JSONB       NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast per-user history queries
CREATE INDEX IF NOT EXISTS lesson_history_user_id_idx
  ON public.lesson_history(user_id, created_at DESC);

-- ── 3. Row Level Security ───────────────────────────────────
-- Users can only read/write their own data.

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_history ENABLE ROW LEVEL SECURITY;

-- profiles: owner-only access
CREATE POLICY "profiles_select_own"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- lesson_history: owner-only access
CREATE POLICY "lesson_history_select_own"
  ON public.lesson_history FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "lesson_history_insert_own"
  ON public.lesson_history FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ── 4. Service-role bypass ──────────────────────────────────
-- API routes use the anon key + user session, but allow
-- server-side inserts via service role when needed.

CREATE POLICY "profiles_insert_service_role"
  ON public.profiles FOR INSERT
  WITH CHECK (true);

-- ── 5. Auto-create profile on signup ───────────────────────
-- Trigger: when a new user is created in auth.users,
-- automatically insert a row in public.profiles.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
